# Generated by Django 4.2.7 on 2026-02-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the government office', max_length=200, unique=True)),
                ('code', models.CharField(help_text="Short code for the office (e.g., 'PO' for Passport Office)", max_length=10, unique=True)),
                ('address', models.TextField(help_text='Physical address of the office')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this office is currently operational')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Government Office',
                'verbose_name_plural': 'Government Offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the service (e.g., 'Passport Renewal')", max_length=200)),
                ('code', models.CharField(help_text="Short code for the service (e.g., 'PASS_RENEW')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service')),
                ('service_type', models.CharField(choices=[('citizenship', 'Citizenship Services'), ('passport', 'Passport Services'), ('tax', 'Tax Services'), ('license', 'License Services'), ('registration', 'Registration Services'), ('other', 'Other Services')], help_text='Category of the service', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(default=30, help_text='Estimated service duration in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently available')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority level (lower numbers = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(help_text='Office that provides this service', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='queue_management.office')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['priority', 'name'],
                'unique_together': {('office', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=200)),
                ('citizen_phone', models.CharField(blank=True, max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('completed', 'Completed'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, max_length=100)),
                ('served_by', models.CharField(blank=True, max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='queue_management.service')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['service', 'status'], name='queue_manag_service_c3b57b_idx'), models.Index(fields=['created_at'], name='queue_manag_created_a4e483_idx'), models.Index(fields=['service', 'number'], name='queue_manag_service_e78f88_idx')],
            },
        ),
    ]
